export const SETTING_EXPLANATIONS = Object.freeze({
  interface_preset: "Changes StoryDriver's local color and surface tokens. It does not alter prose, prompts, narration, or story data.",
  reading_width: "Sets the maximum writing column width. Full uses more workspace while keeping prose paragraphs within a readable measure.",
  reading_font: "Selects a bundled system serif or sans-serif stack for prose only. No font is downloaded.",
  prose_size: "Changes rendered prose size immediately. It does not change generated word count or model behavior.",
  line_height: "Changes vertical space between lines of prose. Typical readable values are 1.6 to 2.0.",
  paragraph_spacing: "Changes the rendered gap between prose paragraphs without modifying saved scene text.",
  interface_scale: "Scales interface text and rem-based controls from 90% to 125%. Touch controls retain their minimum size.",
  custom_interface_scale: "Sets an exact interface scale within the supported 90% to 125% range.",
  mobile_scale: "Optionally overrides interface scale on narrow screens. Form inputs remain at least 16 px to prevent browser zoom.",
  composer_size: "Sets the default director-note height. Custom exposes bounded minimum and maximum heights.",
  composer_text: "Changes director-note text size only. It does not affect prose or generated output.",
  director_note_spacing: "Changes line spacing inside the director-note composer.",
  motion: "Off removes optional transitions. Subtle is the default. Full allows richer local transitions while reduced-motion preferences still win.",
  easter_eggs: "Enables two local, silent StoryDriver logo/title interactions. They never modify stories or settings and can be disabled here.",
  provider: "Chooses the local narration provider. StoryDriver preserves cached chunks and falls back according to narration settings.",
  narrator_profile: "Selects a stored local voice, pacing, chunking, and pronunciation profile.",
  voice: "Overrides the profile's local voice when the selected provider supports it.",
  speed: "Changes narration playback and synthesis speed where supported. Extreme values can reduce naturalness.",
  text_follow: "Controls how generated narration highlights the corresponding prose while it plays.",
  prebuffer_chunks: "Controls how many generated audio chunks StoryDriver prepares ahead. Higher values use more memory but reduce gap risk.",
  pronunciation_aliases: "Maps written forms to local spoken forms before synthesis. One alias per line, such as Aeron => AIR-on.",
  lm_studio_url: "Local OpenAI-compatible LM Studio endpoint used by the next generation. StoryDriver rejects non-local service URLs.",
  selected_model: "Chooses a model reported by LM Studio. The loaded model and runtime remain under LM Studio's control.",
  model_id: "Uses an exact local model identifier when model discovery is unavailable or the model is not listed.",
  inference_backend: "Selects StoryDriver's supported LM Studio request contract. Native REST can expose reasoning controls; OpenAI-compatible is the stable default.",
  reasoning_mode: "Requests a native reasoning level when the selected LM Studio route supports it. StoryDriver's mandatory scene planner is separate and always runs.",
  context_length: "Optionally requests a context size through the supported LM Studio route. It does not reload or reconfigure the model silently.",
  memory_budget: "Limits how much relevant structured continuity context StoryDriver includes. Higher values preserve more detail but use more context.",
  native_fallback: "Allows a failed native REST request to retry through the OpenAI-compatible local endpoint.",
  task: "Selects one StoryDriver task whose compact overrides should be edited. Blank values inherit global settings.",
  task_lm_studio_url: "Overrides the local LM Studio endpoint for only the selected task.",
  task_model: "Overrides the model for only the selected task. Leaving it blank inherits the global model.",
  task_model_id: "Uses an exact local model identifier for only the selected task.",
  task_backend: "Overrides the supported LM Studio request contract for only the selected task.",
  task_model_id: "Uses an exact local model identifier for only the selected task.",
  task_backend: "Overrides the supported LM Studio request contract for only the selected task.",
  timeout_seconds: "Limits how long the selected task may wait for a model response. It does not shorten the requested prose.",
  temperature: "Controls randomness in token selection. Lower values are more predictable; higher values increase variation. StoryDriver applies this to the next generation.",
  top_p: "Limits choices to a cumulative probability range. Lower values narrow vocabulary choices; higher values allow more alternatives.",
  top_k: "Limits token selection to the highest-probability candidates when supported. Lower values are more constrained.",
  min_p: "Drops token choices below a probability threshold relative to the strongest choice. Small values preserve variety while trimming unlikely tokens.",
  max_tokens: "Caps model output tokens for the selected task. If too low, prose can end early; larger values permit longer output and may increase latency.",
  repeat_penalty: "Penalizes recently used tokens where supported. Values too high can make diction unstable; values near 1 are gentler.",
  presence_penalty: "Penalizes tokens already present in the output. Positive values encourage topic variation and can reduce consistency when overused.",
  frequency_penalty: "Penalizes tokens according to repetition count. Positive values can reduce repeated wording but may harm natural recurring names.",
  seed: "Reuses a pseudorandom starting value when the runtime supports deterministic sampling. Identical seeds do not guarantee identical output under different runtime conditions.",
  streaming: "Streams visible prose tokens as they arrive. Disabling it waits for the task result but does not bypass planning, review, or state extraction.",
  stop_strings: "Stops model output when an exact configured sequence appears. Use sparingly because an ordinary prose match can cut a scene short.",
  task_notes: "Adds editable instructions for only the selected StoryDriver task. User task notes remain creative authority and are included in the effective prompt order.",
  length_mode: "Sets the normal word-range target for the next request. A concrete director-note length can override this target.",
  custom_min_words: "Sets the lower custom word target. StoryDriver expands meaningful beats rather than authorizing a larger time skip.",
  custom_max_words: "Sets the upper custom word target and corresponding output budget.",
  preview_director_note: "Supplies disposable text for Prompt Preview only. It is not saved as a scene or director note.",
  preview_mode: "Shows how Continue, Regenerate, Rewrite, or Revise changes the effective prompt and scene-version contract.",
  structured_planning: "StoryDriver's structured Scene Contract planner is mandatory on the normal path.",
  chapter_extension: "Allows one bounded continuation when a requested chapter is materially short. It does not change scene-version semantics.",
  adherence_check: "Controls the legacy lightweight adherence check around the mandatory full review. The deliberate quality review remains active.",
  minimum_height: "Sets the custom composer's starting height in pixels within the safe viewport bounds.",
  maximum_height: "Caps custom composer expansion so writing controls remain reachable.",
  breathing: "Selects local automatic breath placement. Natural is restrained; Cinematic uses stronger pauses and requires suitable authorized samples.",
  opacity: "Controls workspace background visibility. The recommended subtle range is roughly 8% to 15%.",
  dim_overlay: "Adds a theme-colored dark layer above the background image and below all writing surfaces.",
  blur: "Softens only the workspace background image. Higher blur may cost more GPU compositing work.",
  saturation: "Adjusts color intensity only for the workspace background image.",
  fit: "Cover fills the workspace, Contain shows the whole image, and Fill explicitly stretches it.",
  position: "Anchors the background image within the workspace when its aspect ratio differs.",
  attachment: "Fixed keeps the image anchored to the workspace; Scroll follows workspace content.",
  rotation: "Selects a local multi-background rotation interval. Rotation is off by default.",
  custom_rotation_seconds: "Sets a custom interval from 30 seconds to 24 hours. Longer intervals reduce distraction and image decoding work.",
  rotation_order: "Cycles selected backgrounds in library order or chooses a different selected image randomly.",
  fade_seconds: "Controls the workspace-only crossfade. Motion Off and reduced-motion preferences remove this transition.",
});

export function explanationKey(name = "") {
  return String(name)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "");
}

export function settingExplanation(name) {
  return SETTING_EXPLANATIONS[explanationKey(name)] || "";
}
